version: 2

project_name: edgebeat

before:
  hooks:
  - go mod tidy

builds:
- id: edgebeat
  main: ./cmd/edgebeat
  binary: edgebeat
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64

archives:
- id: default
  builds:
  - edgebeat
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: jilanisayyad
    name: edgebeat
  header: |
    ## EdgeBeat {{ .Tag }}

    _Released on {{ .Date }}_

    ### Highlights
    - Initial release

    ### Install (GitHub CLI)
    ```bash
    VERSION={{ .Version }}
    OS=$(uname | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m | sed 's/aarch64/arm64/' | sed 's/x86_64/amd64/')
    ASSET="edgebeat_${VERSION}_${OS}_${ARCH}.tar.gz"
    gh release download {{ .Tag }} --repo jilanisayyad/edgebeat --pattern "${ASSET}"
    tar -xzf "${ASSET}"
    sudo mv edgebeat /usr/local/bin/edgebeat
    edgebeat --help
    ```

    ### Install (curl)
    ```bash
    VERSION={{ .Version }}
    OS=$(uname | tr '[:upper:]' '[:lower:]')
    ARCH=$(uname -m | sed 's/aarch64/arm64/' | sed 's/x86_64/amd64/')
    curl -L -o edgebeat.tar.gz \
      "https://github.com/jilanisayyad/edgebeat/releases/download/{{ .Tag }}/edgebeat_${VERSION}_${OS}_${ARCH}.tar.gz"
    tar -xzf edgebeat.tar.gz
    sudo mv edgebeat /usr/local/bin/edgebeat
    edgebeat --help
    ```
  footer: |
    ### Full Changelog
    https://github.com/jilanisayyad/edgebeat/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^chore'
  groups:
  - title: "Features"
    regexp: '^feat'
    order: 0
  - title: "Fixes"
    regexp: '^fix'
    order: 1
  - title: "Performance"
    regexp: '^perf'
    order: 2
  - title: "Refactors"
    regexp: '^refactor'
    order: 3
  - title: "Tests"
    regexp: '^test'
    order: 4
  - title: "Docs"
    regexp: '^docs'
    order: 5
